name: Update dependencies and run documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_and_tag:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: setup containers
        id: cnt
        run: |
          docker run -d --rm -v ${{ github.workspace }}:/var/www/html devopsansiblede/apache:php8 > /dev/null 2>&1
          cnt8=$( docker ps --quiet )
          docker run -d --rm -v ${{ github.workspace }}:/var/www/html devopsansiblede/apache > /dev/null 2>&1
          cnt7=$( docker ps --quiet | sed '/${cnt8}/ d' )
          echo "::set-output name=cnt8::${cnt8}"
          echo "::set-output name=cnt7::${cnt7}"

      - name: run checks with PHP 7
        run: |
          docker exec -i "${{ steps.cnt.outputs.cnt7 }}" composer validate
          docker exec -i "${{ steps.cnt.outputs.cnt7 }}" composer update
          docker exec -i "${{ steps.cnt.outputs.cnt7 }}" composer run-script test

      - name: run checks with PHP 8
        run: |
          docker exec -i "${{ steps.cnt.outputs.cnt8 }}" composer validate
          docker exec -i "${{ steps.cnt.outputs.cnt8 }}" composer update
          docker exec -i "${{ steps.cnt.outputs.cnt8 }}" composer run-script test

      - name: cleanup containers
        run: |
          docker rm -f "${{ steps.cnt.outputs.cnt7 }}" "${{ steps.cnt.outputs.cnt8 }}"

      - name: renew and build documentation
        run: |
          rm -rf docs
          docker run --rm -v ${{ github.workspace }}:/data phpdoc/phpdoc:3 \
            --setting=graphs.enabled=true -d src -t docs \
            --sourcecode --title=TwigForm --no-interaction
          docker run -d -v ${{ github.workspace }}:/data -w /data ubuntu bash -c \
          "cat <<EOF >> docs/css/base.css

          code.prettyprint {
              background: var(--primary-color-lighten);
              border: 1px solid var(--code-border-color);
              border-radius: var(--border-radius-base-size);
              padding: 0.1em 0.4em;
              margin: 0.1em 0.2em;
              font-size: 0.9em !important;
          }
          pre.prettyprint {
              font-size: 0.8em !important;
          }
          EOF
          "

      - name: check if git changes occur
        id: gitcheck
        run: |
          set +e
          git add -A
          git update-index --refresh
          git diff-index --quiet HEAD --
          if [ $? -ne 0 ] && [ $(date +\%u) = 7 ]; then
            echo "::set-output name=push::push"
          else
            echo "::set-output name=push::skip"
          fi

      - name: 'Get Previous tag'
        if: ${{ steps.gitcheck.outputs.push == 'push' }}
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: 'Get next minor version'
        if: ${{ steps.gitcheck.outputs.push == 'push' }}
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ steps.gitcheck.outputs.push == 'push' }}
        with:
          commit_message: Updated documentation
          commit_user_name: GitHub Actions
          commit_user_email: dev@macwinnie.me
          tagging_message: '${{ steps.semvers.outputs.patch }}'
