name: Update Composer dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '11 23 * * 0'

jobs:
  test_and_tag:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: setup containers
        id: cnt
        run: |
          docker run -d --rm -v ${{ github.workspace }}:/var/www/html devopsansiblede/apache:php8 > /dev/null 2>&1
          cnt8=$( docker ps --quiet )
          echo "cnt8=${cnt8}" >> $GITHUB_OUTPUT

      - name: run checks with PHP 8
        run: |
          docker exec -i "${{ steps.cnt.outputs.cnt8 }}" composer validate
          docker exec -i "${{ steps.cnt.outputs.cnt8 }}" composer update
          docker exec -i "${{ steps.cnt.outputs.cnt8 }}" composer run-script test

      - name: check if git changes occur
        id: gitcheck
        run: |
          set +e
          git add -A
          git update-index --refresh
          git diff-index --quiet HEAD --
          if [ $? -ne 0 ] && [ $(date +\%u) = 7 ]; then
            echo "push=push" >> $GITHUB_OUTPUT
          else
            echo "push=skip" >> $GITHUB_OUTPUT
          fi

      - name: 'Get Previous tag'
        if: ${{ steps.gitcheck.outputs.push == 'push' }}
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: 'Get next minor version'
        if: ${{ steps.gitcheck.outputs.push == 'push' }}
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ steps.gitcheck.outputs.push == 'push' }}
        with:
          commit_message: Apply composer update
          commit_user_name: GitHub Actions
          commit_user_email: dev@macwinnie.me
          tagging_message: '${{ steps.semvers.outputs.patch }}'
